server:
  port: 8081

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://localhost:5432/carsharing
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

jwt:
  secret-key: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"
